version: "3.8"

services:
  envoy:
    build: ./envoy
    ports:
      - "10000:10000"
    networks:
      - proxy_network

  backend:
    build: ./go_backend
    ports:
      - "8081:8081"
    networks:
      - proxy_network

  varnish:
    build: ./varnish
    ports:
      - "8080:80"
    networks:
      - proxy_network
  
  hitch:
    image: your-hitch-image
    volumes:
      - /path/to/server.pem:/etc/hitch/server.pem
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
